### PR TITLE
Fix bug on remote transfer initializer

### PR DESCRIPTION
**Pull request by ppascualv**
## Proposed changes

The API responds with an extra parameter `success: true` to avoid crashing the gem when the API is upgraded the rest of the parameters not used from the API respond are ignored

## Types of changes

What types of changes does your code introduce to wetransfer_ruby_sdk?
_Put an `x` in the boxes that apply_

- [ ] Docs (missing or updated docs)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement / maintenance (removing technical debt, performance, tooling, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/WeTransfer/wetransfer_ruby_sdk/blob/master/.github/CONTRIBUTING.md) doc
- [ ] I have added necessary documentation (if appropriate)
- [ ] Code changes are covered by unit tests.
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by arnoFleming** [comment]
@ppascualv Thanks for reporting (and offering a fix for) this issue.

**Comment by arnoFleming** [comment]
@ppascualv The test suite is failing, based on us not sharing API keys with forks. 

Making sure it works __and__ giving you proper attribution would require us to jump through some hoops. 
Please be patient with us on this, will merge this when we find a good way to do this.

**Comment by ppascualv** [comment]
@arnoFleming I'm using my fork on production environment and it's working. 
FYI this bug should be `critical` remote transfers arern't working.

**Comment by arnoFleming** [comment]
@ppascualv Thanks again for adding this!

**Pull request merged**
