### PR TITLE
Add async option for uploads

### PR DESCRIPTION
**Pull request by sirfilip**
## Proposed changes

It adds an option for performing async chunks upload that will increase upload speed

## Types of changes

What types of changes does your code introduce to wetransfer_ruby_sdk?
_Put an `x` in the boxes that apply_

- [ ] Docs (missing or updated docs)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement / maintenance (removing technical debt, performance, tooling, etc...)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/WeTransfer/wetransfer_ruby_sdk/blob/master/.github/CONTRIBUTING.md) doc
- [ ] I have added necessary documentation (if appropriate)
- [x] Code changes are covered by unit tests.
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

In the tests there where a 7 seconds improvement, not sure if it makes a difference since it loads the server 5 times more for each upload

### CODE REVIEW

**Comment by bermannoah** [comment]
👋 I added a thing to the travis config that should squash the missing key issue - can you pull from master again?

**Comment by sirfilip** [comment]
Yup will do that 👍

**Comment by bermannoah** [comment]
@sirfilip couple of questions and then I'd say the idea is approved for refactorin' --> 
- have you run into any issues where it uploads the chunks out of order and errors? We've hit this with a non-SDK implementation.
- bit of an obnoxious one but before we commit to adding a fairly large dependency: have you encountered a way of implementing this without using the concurrency gem?

**Comment by sirfilip** [comment]
@bermannoah i didnt know that the uploads must be in given order, i thought that the url that is generated is responsible for keeping track of the chunks number, as for a non concurrent ruby gem usage it can be avoided and use the native threading to go with a thread safe queue and thread pool but i believe that the solution is much clearer when we use this gem cause it is quite popular and it offers lots of great functionality, if you like i can offer a native threading solution but if the order of the uploads must be preserved then not sure how we can benefit from concurrency of the uploads.

**Comment by bermannoah** [comment]
So very sorry about the delayed response @sirfilip! We've run into some other issues trying to request file upload URLs concurrently and I think it might make sense to close this PR, as I'm not sure concurrency works well with the multi-part-put upload model. (At least as we implement it.) Would that be okay with you?

**Comment by sirfilip** [comment]
@bermannoah I am sorry that it wont do any good,  feel free to close this pr it is all fine by me no worries 👍

**Comment by bermannoah** [comment]
❤️

**Pull request closed without merging**
